apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: harvester-network-controller
    app.kubernetes.io/component: network
    app.kubernetes.io/version: 0.0.1
  name: harvester-network-controller
  namespace: harvester-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harvester-network-controller
rules:
  - apiGroups: [ "network.harvester.cattle.io" ]
    resources: [ "clusternetworks", "nodenetworks", "nodenetworks/status" ]
    verbs: [ "get", "watch", "list", "update", "create", "delete" ]
  - apiGroups: [ "harvester.cattle.io" ]
    resources: [ "settings" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "k8s.cni.cncf.io" ]
    resources: [ "network-attachment-definitions" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "nodes", "configmaps", "events" ]
    verbs: [ "get", "watch", "list", "update", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: harvester-network-controller
    app.kubernetes.io/component: network
    app.kubernetes.io/version: 0.0.1
  name: harvester-network-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harvester-network-controller
subjects:
  - kind: ServiceAccount
    name: harvester-network-controller
    namespace: harvester-system